AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AI-Powered Customer Support Pipeline

  Sample SAM Template for AI-Powered Customer Support Pipeline

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 30
    CodeUri: lambdas/
    LoggingConfig:
      LogFormat: JSON
Resources:
  SupportRequestReceiverFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/support-request-receiver.handler
      Architectures:
      - x86_64
      Events:
        ReceiveSupportRequest:
          Type: Api
          Properties:
            Path: /support-request
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SupportTicketTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SupportRequestQueue.QueueName
      Environment:
        Variables:
          SUPPORT_TICKETS_TABLE: !Ref SupportTicketTable
          SUPPORT_REQUEST_QUEUE: !GetAtt SupportRequestQueue.QueueUrl
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - handlers/support-request-receiver.ts
        Minify: true
        Target: es2020
        Sourcemap: true
        Bundle: true

  SupportRequestProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/support-request-processor.handler
      Architectures:
      - x86_64
      Events:
        ProcessQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt SupportRequestQueue.Arn
            BatchSize: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SupportTicketTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SupportSnsTopic.TopicName
        - Statement:
            - Effect: Allow
              Action: 
                - bedrock:InvokeModel
              Resource:
                - 'arn:aws:bedrock:*::foundation-model/amazon.titan-embed-text-v1'

      Environment:
        Variables:
          SUPPORT_TICKETS_TABLE: !Ref SupportTicketTable
          BEDROCK_MODEL_ID: amazon.titan-embed-text-v1
          SNS_TOPIC_ARN: !GetAtt SupportSnsTopic.TopicArn
          SNS_FAILED_TOPIC_ARN: !GetAtt SupportFailedSnsTopic.TopicArn
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - handlers/support-request-processor.ts
        Minify: true
        Target: es2020
        Sourcemap: true
        Bundle: true

  SupportTicketTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  SupportRequestQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      VisibilityTimeout: 30
      MessageRetentionPeriod: 1209600  # 14 days in seconds
      ReceiveMessageWaitTimeSeconds: 20  # Long polling
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SupportRequestDLQ.Arn
        maxReceiveCount: 3

  SupportRequestDLQ:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      MessageRetentionPeriod: 1209600  # 14 days

  SupportSnsTopic:
    Type: AWS::SNS::Topic
  
  SupportFailedSnsTopic:
    Type: AWS::SNS::Topic

  AdminEmailSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Endpoint: kahov41785@feanzier.com
      Protocol: email
      TopicArn: !GetAtt SupportSnsTopic.TopicArn

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL for Prod stage for Customer Support Pipeline
      function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  
  SnsTopicName:
    Description: SNS topic name for Support Team Notifications
    Value: !GetAtt SupportSnsTopic.TopicName
  
  SnsTopicArn:
    Description: SNS topic ARN for Support Team Notifications
    Value: !Ref SupportSnsTopic
  
  SupportRequestReceiverFunction:
    Description: Lambda Function ARN for Support Request Receiver
    Value: !GetAtt SupportRequestReceiverFunction.Arn

  SupportRequestProcessorFunction:
    Description: Lambda Function ARN for Support Request Processor
    Value: !GetAtt SupportRequestProcessorFunction.Arn
  
  SupportRequestQueue:
    Description: Support Request Queue ARN
    Value: !GetAtt SupportRequestQueue.Arn