AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AI-Powered Customer Support Pipeline

  Sample SAM Template for AI-Powered Customer Support Pipeline

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 30
    CodeUri: lambdas/

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  SupportRequestReceiverFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/support-request-receiver.handler
      Architectures:
      - x86_64
      Events:
        ReceiveSupportRequest:
          Type: Api
          Properties:
            Path: /support-request
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SupportTicketTable
        - SQSSendMessagePolicy:
            QueueName: SupportRequestQueue
      Environment:
        Variables:
          SUPPORT_TICKETS_TABLE: !Ref SupportTicketTable
          SUPPORT_REQUEST_QUEUE: !GetAtt SupportRequestQueue.QueueUrl
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true

  SupportRequestProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handlers/support-request-processor.handler
      Architectures:
      - x86_64
      Events:
        ProcessQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt SupportRequestQueue.Arn
            BatchSize: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SupportTicketTable
      Environment:
        Variables:
          SUPPORT_TICKETS_TABLE: !Ref SupportTicketTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true

  SupportTicketTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  SupportRequestQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      QueueName: SupportRequestQueue
      VisibilityTimeout: 30
      MessageRetentionPeriod: 1209600  # 14 days in seconds
      ReceiveMessageWaitTimeSeconds: 20  # Long polling
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SupportRequestDLQ.Arn
        maxReceiveCount: 3

  SupportRequestDLQ:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      QueueName: SupportRequestDLQ
      MessageRetentionPeriod: 1209600  # 14 days

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL for Prod stage for Customer Support Pipeline
      function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/Prod/"
  SupportRequestReceiverFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt SupportRequestReceiverFunction.Arn
  SupportRequestQueue:
    Description: Support Request Queue ARN
    Value: !GetAtt SupportRequestQueue.Arn