AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AI-Powered Customer Support Pipeline
Parameters:
  StageName:
    Type: String
    Default: Dev

Globals:
  Function:
    Runtime: nodejs24.x
    Timeout: 30
    CodeUri: lambdas/
    LoggingConfig:
      LogFormat: JSON

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: !Ref StageName
      Name: !Sub '${AWS::StackName}-HttpApi'
    
  SupportRequestReceiverFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-ReceiverFunction'
      Handler: handlers/support-request-receiver.handler
      Architectures:
      - x86_64
      Events:
        ReceiveSupportRequest:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /support-request
            Method: post
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SupportTicketTable
        - SQSSendMessagePolicy:
            QueueName: !GetAtt SupportRequestQueue.QueueName
      Environment:
        Variables:
          SUPPORT_TICKETS_TABLE: !Ref SupportTicketTable
          SUPPORT_REQUEST_QUEUE: !GetAtt SupportRequestQueue.QueueUrl
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - handlers/support-request-receiver.ts
        Minify: true
        Target: es2020
        Sourcemap: true
        Bundle: true

  FetchSupportRequestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-FetchFunction'
      Handler: handlers/fetch-support-ticket.handler
      Architectures:
      - x86_64
      Events:
        FetchSupportRequest:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /support-request
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SupportTicketTable
      Environment:
        Variables:
          SUPPORT_TICKETS_TABLE: !Ref SupportTicketTable
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - handlers/fetch-support-ticket.ts
        Minify: true
        Target: es2020
        Sourcemap: true
        Bundle: true

  SupportRequestProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-ProcessorFunction'
      Handler: handlers/support-request-processor.handler
      Architectures:
      - x86_64
      Events:
        ProcessQueue:
          Type: SQS
          Properties:
            Queue: !GetAtt SupportRequestQueue.Arn
            BatchSize: 10
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref SupportTicketTable
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt SupportTicketNotificationTopic.TopicName
        - Statement:
            - Effect: Allow
              Action: 
                - bedrock:InvokeModel
              Resource:
                - 'arn:aws:bedrock:*::foundation-model/amazon.nova-lite-v1:0'
            - Effect: Allow
              Action: 
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - !GetAtt BedrockTicketProcessorErrorLogGroup.Arn
                - !Sub '${BedrockTicketProcessorErrorLogGroup.Arn}:*'
      Environment:
        Variables:
          SUPPORT_TICKETS_TABLE: !Ref SupportTicketTable
          BEDROCK_MODEL_ID: amazon.nova-lite-v1:0
          SNS_TOPIC_ARN: !GetAtt SupportTicketNotificationTopic.TopicArn
          ERROR_LOG_GROUP_NAME: !Ref BedrockTicketProcessorErrorLogGroup
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        EntryPoints:
          - handlers/support-request-processor.ts
        Minify: true
        Target: es2020
        Sourcemap: true
        Bundle: true

  SupportTicketTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TableName: !Sub '${AWS::StackName}-Table'
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      SSESpecification:
        SSEEnabled: true

  SupportRequestQueue:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      QueueName: !Sub '${AWS::StackName}-RequestQueue'
      VisibilityTimeout: 30
      MessageRetentionPeriod: 1209600  # 14 days in seconds
      ReceiveMessageWaitTimeSeconds: 20  # Long polling
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt SupportRequestDLQ.Arn
        maxReceiveCount: 3

  SupportRequestDLQ:
    Type: AWS::SQS::Queue
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      QueueName: !Sub '${AWS::StackName}-RequestDLQ'
      MessageRetentionPeriod: 1209600  # 14 days

  SupportTicketNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-TicketNotifications'
      Tags:
      - Key: Purpose
        Value: SupportTicketNotifications
      - Key: SubscriptionType
        Value: SelfService

  BedrockTicketProcessorErrorLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '${AWS::StackName}-BedrockTicketProcessorErrorLogGroup'
      RetentionInDays: 30
  
  BedrockTicketProcessorErrorMetricFilter:
    Type: AWS::Logs::MetricFilter
    Properties:
      LogGroupName: !Ref BedrockTicketProcessorErrorLogGroup
      FilterPattern: '{ $.level = "ERROR" && $.service = "BedrockTicketProcessor" }'
      MetricTransformations:
        - MetricName: BedrockTicketProcessorErrors
          MetricNamespace: SupportPipeline
          MetricValue: 1
          DefaultValue: 0
  
  BedrockTicketProcessorErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-BedrockTicketProcessorErrors'
      AlarmDescription: 'Alerts when Bedrock Ticket Processor errors occur'
      MetricName: BedrockTicketProcessorErrors
      Namespace: SupportPipeline
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !Ref BedrockTicketProcessorErrorAlertTopic
      TreatMissingData: notBreaching
  
  BedrockTicketProcessorErrorAlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub '${AWS::StackName}-BedrockTicketProcessorErrorAlerts'

Outputs:
  HttpApiUrl:
    Description: API Gateway endpoint URL
    Value:
      Fn::Sub: 'https://${HttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}/'
  HttpApiId:
    Description: Api id of HttpApi
    Value:
      Ref: HttpApi

  SupportRequestReceiverFunction:
    Description: Lambda Function ARN for Support Request Receiver
    Value: !GetAtt SupportRequestReceiverFunction.Arn

  SupportRequestProcessorFunction:
    Description: Lambda Function ARN for Support Request Processor
    Value: !GetAtt SupportRequestProcessorFunction.Arn
  
  SupportRequestQueue:
    Description: Support Request Queue ARN
    Value: !GetAtt SupportRequestQueue.Arn
  
  SupportTicketNotificationTopicArn:
    Description: SNS Topic ARN for Support Ticket Notifications - Share this with admins to subscribe
    Value: !Ref SupportTicketNotificationTopic
    Export:
      Name: !Sub '${AWS::StackName}-TicketNotificationTopicArn'
  
  BedrockErrorAlertTopicArn:
    Description: SNS Topic ARN for Bedrock Error Alerts - Share this with technical admins to subscribe
    Value: !Ref BedrockTicketProcessorErrorAlertTopic

  SubscriptionInstructions:
    Description: Instructions for subscribing to notifications
    Value: "Use the SNS Topic ARNs above to subscribe via AWS Console, CLI, or SDK. See deployment guide for details."